#!/usr/bin/python

import os

os.system('wget http://d0.fileblock.info/XP.7z')
os.system('wget http://d0.fileblock.info/VISTA.7z')
os.system('wget http://d0.fileblock.info/WIN2K3.7z')
os.system('wget http://d0.fileblock.info/WIN7.7z')
os.system('wget http://d0.fileblock.info/WIN2K8.7z')
os.system('wget http://d0.fileblock.info/WIN8.7z')
os.system('wget http://d0.fileblock.info/WIN2K12.7z')

os.system('p7zip -d XP.7z') 
os.system('p7zip -d VISTA.7z')
os.system('p7zip -d WIN2K3.7z')
os.system('p7zip -d WIN7.7z')
os.system('p7zip -d WIN2K8.7z')
os.system('p7zip -d WIN8.7z')
os.system('p7zip -d WIN2K12.7z')

os.system('hashdb create FileBlock.White')
os.system('hashdb import FileBlock.White WhiteList-XP.DFXML')
os.system('hashdb import FileBlock.White WhiteList-VISTA.DFXML')
os.system('hashdb import FileBlock.White WhiteList-WIN2K3.DFXML')
os.system('hashdb import FileBlock.White WhiteList-WIN7.DFXML')
os.system('hashdb import FileBlock.White WhiteList-WIN2K8.DFXML')
os.system('hashdb import FileBlock.White WhiteList-WIN8.DFXML')
os.system('hashdb import FileBlock.White WhiteList-WIN2K12.DFXML')
os.system('hashdb size FileBlock.White')

os.system('wget http://d0.fileblock.info/VxShare000.7z')
os.system('wget http://d0.fileblock.info/VxShare001.7z')
os.system('wget http://d0.fileblock.info/VxShare002.7z')
os.system('wget http://d0.fileblock.info/VxShare003.7z')
os.system('wget http://d0.fileblock.info/VxShare004.7z')
os.system('wget http://d0.fileblock.info/VxShare005.7z')
os.system('wget http://d0.fileblock.info/VxShare006.7z')
os.system('wget http://d0.fileblock.info/VxShare007.7z')
os.system('wget http://d0.fileblock.info/VxShare008.7z')
os.system('wget http://d0.fileblock.info/VxShare009.7z')
os.system('wget http://d0.fileblock.info/VxShare010.7z')
os.system('wget http://d0.fileblock.info/VxShare011.7z')
os.system('wget http://d0.fileblock.info/VxShare012.7z')
os.system('wget http://d0.fileblock.info/VxShare013.7z')
os.system('wget http://d0.fileblock.info/VxShare014.7z')
os.system('wget http://d0.fileblock.info/VxShare015.7z')
os.system('wget http://d0.fileblock.info/VxShare016.7z')
os.system('wget http://d0.fileblock.info/VxShare017.7z')
os.system('wget http://d0.fileblock.info/VxShare018.7z')
os.system('wget http://d0.fileblock.info/VxShare019.7z')
os.system('wget http://d0.fileblock.info/VxShare020.7z')
os.system('wget http://d0.fileblock.info/VxShare021.7z')
os.system('wget http://d0.fileblock.info/VxShare022.7z')
os.system('wget http://d0.fileblock.info/VxShare023.7z')
os.system('wget http://d0.fileblock.info/VxShare024.7z')
os.system('wget http://d0.fileblock.info/VxShare025.7z')
os.system('wget http://d0.fileblock.info/VxShare026.7z')
os.system('wget http://d0.fileblock.info/VxShare027.7z')
os.system('wget http://d0.fileblock.info/VxShare028.7z')
os.system('wget http://d0.fileblock.info/VxShare029.7z')
os.system('wget http://d0.fileblock.info/VxShare030.7z')
os.system('wget http://d0.fileblock.info/VxShare031.7z')
os.system('wget http://d0.fileblock.info/VxShare032.7z')
os.system('wget http://d0.fileblock.info/VxShare033.7z')
os.system('wget http://d0.fileblock.info/VxShare034.7z')
os.system('wget http://d0.fileblock.info/VxShare035.7z')
os.system('wget http://d0.fileblock.info/VxShare036.7z')
os.system('wget http://d0.fileblock.info/VxShare037.7z')
os.system('wget http://d0.fileblock.info/VxShare038.7z')
os.system('wget http://d0.fileblock.info/VxShare039.7z')
os.system('wget http://d0.fileblock.info/VxShare040.7z')
os.system('wget http://d0.fileblock.info/VxShare041.7z')
os.system('wget http://d0.fileblock.info/VxShare042.7z')
os.system('wget http://d0.fileblock.info/VxShare043.7z')
os.system('wget http://d0.fileblock.info/VxShare044.7z')
os.system('wget http://d0.fileblock.info/VxShare045.7z')
os.system('wget http://d0.fileblock.info/VxShare046.7z')
os.system('wget http://d0.fileblock.info/VxShare047.7z')
os.system('wget http://d0.fileblock.info/VxShare048.7z')
os.system('wget http://d0.fileblock.info/VxShare049.7z')
os.system('wget http://d0.fileblock.info/VxShare050.7z')
os.system('wget http://d0.fileblock.info/VxShare051.7z')
os.system('wget http://d0.fileblock.info/VxShare052.7z')
os.system('wget http://d0.fileblock.info/VxShare053.7z')
os.system('wget http://d0.fileblock.info/VxShare054.7z')
os.system('wget http://d0.fileblock.info/VxShare055.7z')
os.system('wget http://d0.fileblock.info/VxShare056.7z')
os.system('wget http://d0.fileblock.info/VxShare057.7z')
os.system('wget http://d0.fileblock.info/VxShare058.7z')
os.system('wget http://d0.fileblock.info/VxShare059.7z')
os.system('wget http://d0.fileblock.info/VxShare060.7z')
os.system('wget http://d0.fileblock.info/VxShare061.7z')
os.system('wget http://d0.fileblock.info/VxShare062.7z')
os.system('wget http://d0.fileblock.info/VxShare063.7z')
os.system('wget http://d0.fileblock.info/VxShare064.7z')
os.system('wget http://d0.fileblock.info/VxShare065.7z')
os.system('wget http://d0.fileblock.info/VxShare066.7z')
os.system('wget http://d0.fileblock.info/VxShare067.7z')
os.system('wget http://d0.fileblock.info/VxShare068.7z')
os.system('wget http://d0.fileblock.info/VxShare069.7z')
os.system('wget http://d0.fileblock.info/VxShare070.7z')
os.system('wget http://d0.fileblock.info/VxShare071.7z')
os.system('wget http://d0.fileblock.info/VxShare072.7z')
os.system('wget http://d0.fileblock.info/VxShare073.7z')
os.system('wget http://d0.fileblock.info/VxShare074.7z')
os.system('wget http://d0.fileblock.info/VxShare075.7z')
os.system('wget http://d0.fileblock.info/VxShare076.7z')
os.system('wget http://d0.fileblock.info/VxShare077.7z')
os.system('wget http://d0.fileblock.info/VxShare078.7z')
os.system('wget http://d0.fileblock.info/VxShare079.7z')
os.system('wget http://d0.fileblock.info/VxShare080.7z')
os.system('wget http://d0.fileblock.info/VxShare081.7z')
os.system('wget http://d0.fileblock.info/VxShare082.7z')
os.system('wget http://d0.fileblock.info/VxShare083.7z')
os.system('wget http://d0.fileblock.info/VxShare084.7z')
os.system('wget http://d0.fileblock.info/VxShare085.7z')
os.system('wget http://d0.fileblock.info/VxShare086.7z')
os.system('wget http://d0.fileblock.info/VxShare087.7z')
os.system('wget http://d0.fileblock.info/VxShare088.7z')
os.system('wget http://d0.fileblock.info/VxShare089.7z')
os.system('wget http://d0.fileblock.info/VxShare090.7z')
os.system('wget http://d1.fileblock.info/VxShare091.7z')
os.system('wget http://d1.fileblock.info/VxShare092.7z')
os.system('wget http://d1.fileblock.info/VxShare093.7z')
os.system('wget http://d1.fileblock.info/VxShare094.7z')
os.system('wget http://d1.fileblock.info/VxShare095.7z')
os.system('wget http://d1.fileblock.info/VxShare096.7z')
os.system('wget http://d1.fileblock.info/VxShare097.7z')
os.system('wget http://d1.fileblock.info/VxShare098.7z')
os.system('wget http://d1.fileblock.info/VxShare099.7z')
os.system('wget http://d1.fileblock.info/VxShare100.7z')
os.system('wget http://d1.fileblock.info/VxShare101.7z')
os.system('wget http://d1.fileblock.info/VxShare102.7z')
os.system('wget http://d1.fileblock.info/VxShare103.7z')
os.system('wget http://d1.fileblock.info/VxShare104.7z')
os.system('wget http://d1.fileblock.info/VxShare105.7z')
os.system('wget http://d1.fileblock.info/VxShare106.7z')
os.system('wget http://d1.fileblock.info/VxShare107.7z')
os.system('wget http://d1.fileblock.info/VxShare108.7z')
os.system('wget http://d1.fileblock.info/VxShare109.7z')
os.system('wget http://d1.fileblock.info/VxShare110.7z')
os.system('wget http://d1.fileblock.info/VxShare111.7z')
os.system('wget http://d1.fileblock.info/VxShare112.7z')
os.system('wget http://d1.fileblock.info/VxShare113.7z')
os.system('wget http://d1.fileblock.info/VxShare114.7z')
os.system('wget http://d1.fileblock.info/VxShare115.7z')
os.system('wget http://d1.fileblock.info/VxShare116.7z')
os.system('wget http://d1.fileblock.info/VxShare117.7z')
os.system('wget http://d1.fileblock.info/VxShare118.7z')
os.system('wget http://d1.fileblock.info/VxShare119.7z')
os.system('wget http://d1.fileblock.info/VxShare120.7z')
os.system('wget http://d1.fileblock.info/VxShare121.7z')
os.system('wget http://d1.fileblock.info/VxShare122.7z')
os.system('wget http://d1.fileblock.info/VxShare123.7z')
os.system('wget http://d1.fileblock.info/VxShare124.7z')
os.system('wget http://d1.fileblock.info/VxShare125.7z')
os.system('wget http://d1.fileblock.info/VxShare126.7z')
os.system('wget http://d1.fileblock.info/VxShare127.7z')
os.system('wget http://d1.fileblock.info/VxShare128.7z')
os.system('wget http://d1.fileblock.info/VxShare129.7z')
os.system('wget http://d1.fileblock.info/VxShare130.7z')
os.system('wget http://d1.fileblock.info/VxShare131.7z')
os.system('wget http://d1.fileblock.info/VxShare132.7z')
os.system('wget http://d1.fileblock.info/VxShare133.7z')
os.system('wget http://d1.fileblock.info/VxShare134.7z')
os.system('wget http://d1.fileblock.info/VxShare135.7z')
os.system('wget http://d1.fileblock.info/VxShare136.7z')
os.system('wget http://d1.fileblock.info/VxShare137.7z')
os.system('wget http://d1.fileblock.info/VxShare138.7z')
os.system('wget http://d1.fileblock.info/VxShare139.7z')
os.system('wget http://d1.fileblock.info/VxShare140.7z')
os.system('wget http://d1.fileblock.info/VxShare141.7z')
os.system('wget http://d1.fileblock.info/VxShare142.7z')
os.system('wget http://d1.fileblock.info/VxShare143.7z')
os.system('wget http://d1.fileblock.info/VxShare144.7z')
os.system('wget http://d1.fileblock.info/VxShare145.7z')
os.system('wget http://d1.fileblock.info/VxShare146.7z')
os.system('wget http://d1.fileblock.info/VxShare147.7z')
os.system('wget http://d1.fileblock.info/VxShare148.7z')
os.system('wget http://d1.fileblock.info/VxShare149.7z')
os.system('wget http://d1.fileblock.info/VxShare150.7z')

os.system('p7zip -d VxShare000.7z')
os.system('p7zip -d VxShare001.7z')
os.system('p7zip -d VxShare002.7z')
os.system('p7zip -d VxShare003.7z')
os.system('p7zip -d VxShare004.7z')
os.system('p7zip -d VxShare005.7z')
os.system('p7zip -d VxShare006.7z')
os.system('p7zip -d VxShare007.7z')
os.system('p7zip -d VxShare008.7z')
os.system('p7zip -d VxShare009.7z')
os.system('p7zip -d VxShare010.7z')
os.system('p7zip -d VxShare011.7z')
os.system('p7zip -d VxShare012.7z')
os.system('p7zip -d VxShare013.7z')
os.system('p7zip -d VxShare014.7z')
os.system('p7zip -d VxShare015.7z')
os.system('p7zip -d VxShare016.7z')
os.system('p7zip -d VxShare017.7z')
os.system('p7zip -d VxShare018.7z')
os.system('p7zip -d VxShare019.7z')
os.system('p7zip -d VxShare020.7z')
os.system('p7zip -d VxShare021.7z')
os.system('p7zip -d VxShare022.7z')
os.system('p7zip -d VxShare023.7z')
os.system('p7zip -d VxShare024.7z')
os.system('p7zip -d VxShare025.7z')
os.system('p7zip -d VxShare026.7z')
os.system('p7zip -d VxShare027.7z')
os.system('p7zip -d VxShare028.7z')
os.system('p7zip -d VxShare029.7z')
os.system('p7zip -d VxShare030.7z')
os.system('p7zip -d VxShare031.7z')
os.system('p7zip -d VxShare032.7z')
os.system('p7zip -d VxShare033.7z')
os.system('p7zip -d VxShare034.7z')
os.system('p7zip -d VxShare035.7z')
os.system('p7zip -d VxShare036.7z')
os.system('p7zip -d VxShare037.7z')
os.system('p7zip -d VxShare038.7z')
os.system('p7zip -d VxShare039.7z')
os.system('p7zip -d VxShare040.7z')
os.system('p7zip -d VxShare041.7z')
os.system('p7zip -d VxShare042.7z')
os.system('p7zip -d VxShare043.7z')
os.system('p7zip -d VxShare044.7z')
os.system('p7zip -d VxShare045.7z')
os.system('p7zip -d VxShare046.7z')
os.system('p7zip -d VxShare047.7z')
os.system('p7zip -d VxShare048.7z')
os.system('p7zip -d VxShare049.7z')
os.system('p7zip -d VxShare050.7z')
os.system('p7zip -d VxShare051.7z')
os.system('p7zip -d VxShare052.7z')
os.system('p7zip -d VxShare053.7z')
os.system('p7zip -d VxShare054.7z')
os.system('p7zip -d VxShare055.7z')
os.system('p7zip -d VxShare056.7z')
os.system('p7zip -d VxShare057.7z')
os.system('p7zip -d VxShare058.7z')
os.system('p7zip -d VxShare059.7z')
os.system('p7zip -d VxShare060.7z')
os.system('p7zip -d VxShare061.7z')
os.system('p7zip -d VxShare062.7z')
os.system('p7zip -d VxShare063.7z')
os.system('p7zip -d VxShare064.7z')
os.system('p7zip -d VxShare065.7z')
os.system('p7zip -d VxShare066.7z')
os.system('p7zip -d VxShare067.7z')
os.system('p7zip -d VxShare068.7z')
os.system('p7zip -d VxShare069.7z')
os.system('p7zip -d VxShare070.7z')
os.system('p7zip -d VxShare071.7z')
os.system('p7zip -d VxShare072.7z')
os.system('p7zip -d VxShare073.7z')
os.system('p7zip -d VxShare074.7z')
os.system('p7zip -d VxShare075.7z')
os.system('p7zip -d VxShare076.7z')
os.system('p7zip -d VxShare077.7z')
os.system('p7zip -d VxShare078.7z')
os.system('p7zip -d VxShare079.7z')
os.system('p7zip -d VxShare080.7z')
os.system('p7zip -d VxShare081.7z')
os.system('p7zip -d VxShare082.7z')
os.system('p7zip -d VxShare083.7z')
os.system('p7zip -d VxShare084.7z')
os.system('p7zip -d VxShare085.7z')
os.system('p7zip -d VxShare086.7z')
os.system('p7zip -d VxShare087.7z')
os.system('p7zip -d VxShare088.7z')
os.system('p7zip -d VxShare089.7z')
os.system('p7zip -d VxShare090.7z')
os.system('p7zip -d VxShare091.7z')
os.system('p7zip -d VxShare092.7z')
os.system('p7zip -d VxShare093.7z')
os.system('p7zip -d VxShare094.7z')
os.system('p7zip -d VxShare095.7z')
os.system('p7zip -d VxShare096.7z')
os.system('p7zip -d VxShare097.7z')
os.system('p7zip -d VxShare098.7z')
os.system('p7zip -d VxShare099.7z')
os.system('p7zip -d VxShare100.7z')
os.system('p7zip -d VxShare101.7z')
os.system('p7zip -d VxShare102.7z')
os.system('p7zip -d VxShare103.7z')
os.system('p7zip -d VxShare104.7z')
os.system('p7zip -d VxShare105.7z')
os.system('p7zip -d VxShare106.7z')
os.system('p7zip -d VxShare107.7z')
os.system('p7zip -d VxShare108.7z')
os.system('p7zip -d VxShare109.7z')
os.system('p7zip -d VxShare110.7z')
os.system('p7zip -d VxShare111.7z')
os.system('p7zip -d VxShare112.7z')
os.system('p7zip -d VxShare113.7z')
os.system('p7zip -d VxShare114.7z')
os.system('p7zip -d VxShare115.7z')
os.system('p7zip -d VxShare116.7z')
os.system('p7zip -d VxShare117.7z')
os.system('p7zip -d VxShare118.7z')
os.system('p7zip -d VxShare119.7z')
os.system('p7zip -d VxShare120.7z')
os.system('p7zip -d VxShare121.7z')
os.system('p7zip -d VxShare122.7z')
os.system('p7zip -d VxShare123.7z')
os.system('p7zip -d VxShare124.7z')
os.system('p7zip -d VxShare125.7z')
os.system('p7zip -d VxShare126.7z')
os.system('p7zip -d VxShare127.7z')
os.system('p7zip -d VxShare128.7z')
os.system('p7zip -d VxShare129.7z')
os.system('p7zip -d VxShare130.7z')
os.system('p7zip -d VxShare131.7z')
os.system('p7zip -d VxShare132.7z')
os.system('p7zip -d VxShare133.7z')
os.system('p7zip -d VxShare134.7z')
os.system('p7zip -d VxShare135.7z')
os.system('p7zip -d VxShare136.7z')
os.system('p7zip -d VxShare137.7z')
os.system('p7zip -d VxShare138.7z')
os.system('p7zip -d VxShare139.7z')
os.system('p7zip -d VxShare140.7z')
os.system('p7zip -d VxShare141.7z')
os.system('p7zip -d VxShare142.7z')
os.system('p7zip -d VxShare143.7z')
os.system('p7zip -d VxShare144.7z')
os.system('p7zip -d VxShare145.7z')
os.system('p7zip -d VxShare146.7z')
os.system('p7zip -d VxShare147.7z')
os.system('p7zip -d VxShare148.7z')
os.system('p7zip -d VxShare149.7z')
os.system('p7zip -d VxShare150.7z')

os.system('hashdb create FileBlock.Import')
os.system('hashdb import FileBlock.Import VxShare000.DFXML')
os.system('hashdb import FileBlock.Import VxShare001.DFXML')
os.system('hashdb import FileBlock.Import VxShare002.DFXML')
os.system('hashdb import FileBlock.Import VxShare003.DFXML')
os.system('hashdb import FileBlock.Import VxShare004.DFXML')
os.system('hashdb import FileBlock.Import VxShare005.DFXML')
os.system('hashdb import FileBlock.Import VxShare006.DFXML')
os.system('hashdb import FileBlock.Import VxShare007.DFXML')
os.system('hashdb import FileBlock.Import VxShare008.DFXML')
os.system('hashdb import FileBlock.Import VxShare009.DFXML')
os.system('hashdb import FileBlock.Import VxShare010.DFXML')
os.system('hashdb import FileBlock.Import VxShare011.DFXML')
os.system('hashdb import FileBlock.Import VxShare012.DFXML')
os.system('hashdb import FileBlock.Import VxShare013.DFXML')
os.system('hashdb import FileBlock.Import VxShare014.DFXML')
os.system('hashdb import FileBlock.Import VxShare015.DFXML')
os.system('hashdb import FileBlock.Import VxShare016.DFXML')
os.system('hashdb import FileBlock.Import VxShare017.DFXML')
os.system('hashdb import FileBlock.Import VxShare018.DFXML')
os.system('hashdb import FileBlock.Import VxShare019.DFXML')
os.system('hashdb import FileBlock.Import VxShare020.DFXML')
os.system('hashdb import FileBlock.Import VxShare021.DFXML')
os.system('hashdb import FileBlock.Import VxShare022.DFXML')
os.system('hashdb import FileBlock.Import VxShare023.DFXML')
os.system('hashdb import FileBlock.Import VxShare024.DFXML')
os.system('hashdb import FileBlock.Import VxShare025.DFXML')
os.system('hashdb import FileBlock.Import VxShare026.DFXML')
os.system('hashdb import FileBlock.Import VxShare027.DFXML')
os.system('hashdb import FileBlock.Import VxShare028.DFXML')
os.system('hashdb import FileBlock.Import VxShare029.DFXML')
os.system('hashdb import FileBlock.Import VxShare030.DFXML')
os.system('hashdb import FileBlock.Import VxShare031.DFXML')
os.system('hashdb import FileBlock.Import VxShare032.DFXML')
os.system('hashdb import FileBlock.Import VxShare033.DFXML')
os.system('hashdb import FileBlock.Import VxShare034.DFXML')
os.system('hashdb import FileBlock.Import VxShare035.DFXML')
os.system('hashdb import FileBlock.Import VxShare036.DFXML')
os.system('hashdb import FileBlock.Import VxShare037.DFXML')
os.system('hashdb import FileBlock.Import VxShare038.DFXML')
os.system('hashdb import FileBlock.Import VxShare039.DFXML')
os.system('hashdb import FileBlock.Import VxShare040.DFXML')
os.system('hashdb import FileBlock.Import VxShare041.DFXML')
os.system('hashdb import FileBlock.Import VxShare042.DFXML')
os.system('hashdb import FileBlock.Import VxShare043.DFXML')
os.system('hashdb import FileBlock.Import VxShare044.DFXML')
os.system('hashdb import FileBlock.Import VxShare045.DFXML')
os.system('hashdb import FileBlock.Import VxShare046.DFXML')
os.system('hashdb import FileBlock.Import VxShare047.DFXML')
os.system('hashdb import FileBlock.Import VxShare048.DFXML')
os.system('hashdb import FileBlock.Import VxShare049.DFXML')
os.system('hashdb import FileBlock.Import VxShare050.DFXML')
os.system('hashdb import FileBlock.Import VxShare051.DFXML')
os.system('hashdb import FileBlock.Import VxShare052.DFXML')
os.system('hashdb import FileBlock.Import VxShare053.DFXML')
os.system('hashdb import FileBlock.Import VxShare054.DFXML')
os.system('hashdb import FileBlock.Import VxShare055.DFXML')
os.system('hashdb import FileBlock.Import VxShare056.DFXML')
os.system('hashdb import FileBlock.Import VxShare057.DFXML')
os.system('hashdb import FileBlock.Import VxShare058.DFXML')
os.system('hashdb import FileBlock.Import VxShare059.DFXML')
os.system('hashdb import FileBlock.Import VxShare060.DFXML')
os.system('hashdb import FileBlock.Import VxShare061.DFXML')
os.system('hashdb import FileBlock.Import VxShare062.DFXML')
os.system('hashdb import FileBlock.Import VxShare063.DFXML')
os.system('hashdb import FileBlock.Import VxShare064.DFXML')
os.system('hashdb import FileBlock.Import VxShare065.DFXML')
os.system('hashdb import FileBlock.Import VxShare066.DFXML')
os.system('hashdb import FileBlock.Import VxShare067.DFXML')
os.system('hashdb import FileBlock.Import VxShare068.DFXML')
os.system('hashdb import FileBlock.Import VxShare069.DFXML')
os.system('hashdb import FileBlock.Import VxShare070.DFXML')
os.system('hashdb import FileBlock.Import VxShare071.DFXML')
os.system('hashdb import FileBlock.Import VxShare072.DFXML')
os.system('hashdb import FileBlock.Import VxShare073.DFXML')
os.system('hashdb import FileBlock.Import VxShare074.DFXML')
os.system('hashdb import FileBlock.Import VxShare075.DFXML')
os.system('hashdb import FileBlock.Import VxShare076.DFXML')
os.system('hashdb import FileBlock.Import VxShare077.DFXML')
os.system('hashdb import FileBlock.Import VxShare078.DFXML')
os.system('hashdb import FileBlock.Import VxShare079.DFXML')
os.system('hashdb import FileBlock.Import VxShare080.DFXML')
os.system('hashdb import FileBlock.Import VxShare081.DFXML')
os.system('hashdb import FileBlock.Import VxShare082.DFXML')
os.system('hashdb import FileBlock.Import VxShare083.DFXML')
os.system('hashdb import FileBlock.Import VxShare084.DFXML')
os.system('hashdb import FileBlock.Import VxShare085.DFXML')
os.system('hashdb import FileBlock.Import VxShare086.DFXML')
os.system('hashdb import FileBlock.Import VxShare087.DFXML')
os.system('hashdb import FileBlock.Import VxShare088.DFXML')
os.system('hashdb import FileBlock.Import VxShare089.DFXML')
os.system('hashdb import FileBlock.Import VxShare090.DFXML')
os.system('hashdb import FileBlock.Import VxShare091.DFXML')
os.system('hashdb import FileBlock.Import VxShare092.DFXML')
os.system('hashdb import FileBlock.Import VxShare093.DFXML')
os.system('hashdb import FileBlock.Import VxShare094.DFXML')
os.system('hashdb import FileBlock.Import VxShare095.DFXML')
os.system('hashdb import FileBlock.Import VxShare096.DFXML')
os.system('hashdb import FileBlock.Import VxShare097.DFXML')
os.system('hashdb import FileBlock.Import VxShare098.DFXML')
os.system('hashdb import FileBlock.Import VxShare099.DFXML')
os.system('hashdb import FileBlock.Import VxShare100.DFXML')
os.system('hashdb import FileBlock.Import VxShare101.DFXML')
os.system('hashdb import FileBlock.Import VxShare102.DFXML')
os.system('hashdb import FileBlock.Import VxShare103.DFXML')
os.system('hashdb import FileBlock.Import VxShare104.DFXML')
os.system('hashdb import FileBlock.Import VxShare105.DFXML')
os.system('hashdb import FileBlock.Import VxShare106.DFXML')
os.system('hashdb import FileBlock.Import VxShare107.DFXML')
os.system('hashdb import FileBlock.Import VxShare108.DFXML')
os.system('hashdb import FileBlock.Import VxShare109.DFXML')
os.system('hashdb import FileBlock.Import VxShare110.DFXML')
os.system('hashdb import FileBlock.Import VxShare111.DFXML')
os.system('hashdb import FileBlock.Import VxShare112.DFXML')
os.system('hashdb import FileBlock.Import VxShare113.DFXML')
os.system('hashdb import FileBlock.Import VxShare114.DFXML')
os.system('hashdb import FileBlock.Import VxShare115.DFXML')
os.system('hashdb import FileBlock.Import VxShare116.DFXML')
os.system('hashdb import FileBlock.Import VxShare117.DFXML')
os.system('hashdb import FileBlock.Import VxShare118.DFXML')
os.system('hashdb import FileBlock.Import VxShare119.DFXML')
os.system('hashdb import FileBlock.Import VxShare120.DFXML')
os.system('hashdb import FileBlock.Import VxShare121.DFXML')
os.system('hashdb import FileBlock.Import VxShare122.DFXML')
os.system('hashdb import FileBlock.Import VxShare123.DFXML')
os.system('hashdb import FileBlock.Import VxShare124.DFXML')
os.system('hashdb import FileBlock.Import VxShare125.DFXML')
os.system('hashdb import FileBlock.Import VxShare126.DFXML')
os.system('hashdb import FileBlock.Import VxShare127.DFXML')
os.system('hashdb import FileBlock.Import VxShare128.DFXML')
os.system('hashdb import FileBlock.Import VxShare129.DFXML')
os.system('hashdb import FileBlock.Import VxShare130.DFXML')
os.system('hashdb import FileBlock.Import VxShare131.DFXML')
os.system('hashdb import FileBlock.Import VxShare132.DFXML')
os.system('hashdb import FileBlock.Import VxShare133.DFXML')
os.system('hashdb import FileBlock.Import VxShare134.DFXML')
os.system('hashdb import FileBlock.Import VxShare135.DFXML')
os.system('hashdb import FileBlock.Import VxShare136.DFXML')
os.system('hashdb import FileBlock.Import VxShare137.DFXML')
os.system('hashdb import FileBlock.Import VxShare138.DFXML')
os.system('hashdb import FileBlock.Import VxShare139.DFXML')
os.system('hashdb import FileBlock.Import VxShare140.DFXML')
os.system('hashdb import FileBlock.Import VxShare141.DFXML')
os.system('hashdb import FileBlock.Import VxShare142.DFXML')
os.system('hashdb import FileBlock.Import VxShare143.DFXML')
os.system('hashdb import FileBlock.Import VxShare144.DFXML')
os.system('hashdb import FileBlock.Import VxShare145.DFXML')
os.system('hashdb import FileBlock.Import VxShare146.DFXML')
os.system('hashdb import FileBlock.Import VxShare147.DFXML')
os.system('hashdb import FileBlock.Import VxShare148-DFXML.DFXML')
os.system('hashdb import FileBlock.Import VxShare149-DFXML.DFXML')
os.system('hashdb import FileBlock.Import VxShare150.DFXML')
os.system('hashdb size FileBlock.Import')

os.system('hashdb create FileBlock.Info’)
os.system('hashdb subtract FileBlock.Import FileBlock.White FileBlock.Info')
os.system('hashdb size FileBlock.Info')
