sdhash.exe -c bug.sdbf SDBF\VxShare000-SDBF.sdbf > sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare001-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare002-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare003-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare004-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare005-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare006-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare007-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare008-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare009-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare010-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare011-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare012-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare013-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare014-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare015-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare016-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare017-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare018-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare019-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare020-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare021-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare022-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare023-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare024-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare025-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare026-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare027-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare028-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare029-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare030-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare031-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare032-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare033-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare034-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare035-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare036-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare037-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare038-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare039-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare040-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare041-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare042-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare043-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare044-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare045-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare046-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare047-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare048-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare049-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare050-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare051-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare052-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare053-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare054-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare055-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare056-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare057-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare058-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare059-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare060-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare061-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare062-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare063-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare064-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare065-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare066-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare067-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare068-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare069-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare070-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare071-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare072-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare073-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare074-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare075-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare076-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare077-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare078-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare079-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare080-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare081-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare082-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare083-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare084-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare085-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare086-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare087-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare088-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare089-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare090-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare091-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare092-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare093-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare094-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare095-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare096-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare097-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare098-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare099-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare100-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare101-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare102-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare103-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare104-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare105-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare106-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare107-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare108-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare109-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare110-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare111-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare112-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare113-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare114-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare115-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare116-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare117-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare118-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare119-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare120-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare121-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare122-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare123-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare124-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare125-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare126-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare127-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare128-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare129-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare130-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare131-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare132-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare133-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare134-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare135-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare136-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare137-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare138-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare139-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare140-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare141-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare142-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare143-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare144-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare145-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare146-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare147-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare148-SDBF.sdbf >> sdbf.txt
sdhash.exe -c bug.sdbf SDBF\VxShare149-SDBF.sdbf >> sdbf.txt