hashdb.exe create FileBlock.Import
hashdb.exe import FileBlock.Import DFXML\VxShare000.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare001.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare002.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare003.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare004.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare005.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare006.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare007.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare008.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare009.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare010.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare011.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare012.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare013.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare014.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare015.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare016.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare017.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare018.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare019.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare020.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare021.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare022.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare023.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare024.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare025.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare026.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare027.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare028.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare029.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare030.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare031.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare032.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare033.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare034.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare035.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare036.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare037.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare038.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare039.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare040.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare041.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare042.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare043.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare044.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare045.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare046.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare047.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare048.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare049.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare050.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare051.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare052.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare053.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare054.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare055.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare056.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare057.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare058.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare059.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare060.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare061.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare062.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare063.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare064.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare065.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare066.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare067.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare068.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare069.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare070.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare071.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare072.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare073.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare074.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare075.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare076.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare077.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare078.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare079.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare080.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare081.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare082.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare083.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare084.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare085.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare086.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare087.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare088.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare089.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare090.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare091.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare092.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare093.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare094.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare095.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare096.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare097.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare098.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare099.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare100.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare101.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare102.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare103.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare104.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare105.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare106.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare107.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare108.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare109.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare110.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare111.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare112.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare113.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare114.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare115.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare116.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare117.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare118.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare119.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare120.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare121.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare122.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare123.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare124.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare125.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare126.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare127.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare128.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare129.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare130.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare131.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare132.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare133.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare134.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare135.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare136.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare137.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare138.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare139.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare140.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare141.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare142.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare143.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare144.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare145.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare146.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare147.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare148.DFXML
hashdb.exe import FileBlock.Import DFXML\VxShare149.DFXML
hashdb.exe create FileBlock.White
hashdb.exe import FileBlock.White DFXML\WhiteList-XP.DFXML
hashdb.exe import FileBlock.White DFXML\WhiteList-VISTA.DFXML
hashdb.exe import FileBlock.White DFXML\WhiteList-WIN2K3.DFXML
hashdb.exe import FileBlock.White DFXML\WhiteList-WIN7.DFXML
hashdb.exe import FileBlock.White DFXML\WhiteList-WIN2K8.DFXML
hashdb.exe import FileBlock.White DFXML\WhiteList-WIN8.DFXML
hashdb.exe import FileBlock.White DFXML\WhiteList-WIN2K12.DFXML
hashdb.exe create FileBlock.Info
hashdb.exe subtract FileBlock.Import FileBlock.White FileBlock.Info